#!/usr/bin/env node

var targz = require('tar.gz');

var program = require('commander');
program.version('0.0.1');

program.command('compress').description('initialize project configuration').action(function(){
	var compress = new targz().compress('./projects', './projects.tar.gz', function(err){
		if(err)
		console.log(err);

		console.log('The compression has ended!');
	});
});
program.command('deflate').description('initialize project configuration').action(function(){
	var compress = new targz().extract('./projects.tar.gz', './projects2', function(err){
		if(err)
		console.log(err);

		console.log('The extraction has ended!');
	});
});
program.command('').description('default').action(function(){
	console.log('Are you lost?');
});
program.command('bye [name]').description('initialize project configuration').action(function(name){
	console.log('Bye ' + name + '. It was good to see you!');
});
program.command('*').action(function(env){
	console.log('Enter a Valid command');
	terminate(true);
});
program.parse(process.argv);